- hosts: isuservers
  become: true
  vars:
    MYSQL_USER: isucon
    MYSQL_PASS: isucon
    MYSQL_DBNAME: isucondition
  roles:
    # - mysql
    - role: tools
      tags: [tools]
    - role: app
      tags: [app]
    - role: newrelic
      tags: [newrelic]
