- hosts: isuservers
  become: true
  vars:
    MYSQL_USER: isucon
    MYSQL_PASS: isucon
    MYSQL_DBNAME: isucondition
    NGINX_FILES:
      - {
          src: "/etc/nginx/nginx.conf",
          dest: "/home/isucon/webapp/isucondition.conf",
        }
      - {
          src: "/etc/nginx/sites-available/isucondition.conf",
          dest: "/home/isucon/webapp/nginx.conf",
        }
  roles:
    - role: nginx
      tags: [nginx]
    - role: tools
      tags: [tools]
    - role: app
      tags: [app]
    - role: newrelic
      tags: [newrelic]
