- hosts: isuservers
  become: true
  vars:
    MYSQL_USER: isucon
    MYSQL_PASS: isucon
    MYSQL_DBNAME: isuports
    NGINX_FILES:
      - {
          src: "/etc/nginx/nginx.conf",
          dest: "/home/isucon/webapp/nginx_nginx.conf",
        }
      - {
          src: "/etc/nginx/sites-available/isuports.conf",
          dest: "/home/isucon/webapp/sites-available_isuports.conf",
        }
  roles:
    - role: nginx
      tags: [nginx]
    - role: tools
      tags: [tools]
    - role: app
      tags: [app]
    - role: newrelic
      tags: [newrelic]
