- name: check alp
  stat:
    path: /usr/local/bin/alp
  register: alp

- name: download binary file
  get_url:
    name: alp
    url: https://github.com/tkuchiki/alp/releases/download/v1.0.9/alp_linux_amd64.tar.gz
    dest: /tmp
  when: not alp.stat.exists

- name: unarchive
  command: tar -zxvf /tmp/alp_linux_amd64.tar.gz
  when: not alp.stat.exists

- name: enabled
  command: sudo install /tmp/alp /usr/local/bin/alp
  when: not alp.stat.exists

- name: cp Makefile
  copy:
    src: ./files/Makefile
    dest: /home/isucon/Makefile
    owner: isucon
    group: isucon
    mode: "0755"
