- name: git pull
  git:
    repo: git@github.com:reiichii/isucon-study0625.git
    dest: /home/isucon
    clone: no

- name: restart mysql
  service:
    name: mysql
    state: restarted
  become: true

- name: restart web-ruby
  service:
    name: web-ruby
    state: restarted
  become: true

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: true
