- name: cp nginx.conf
  copy:
    src: ./files/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  become: true

- name: cp sites-available/default
  copy:
    src: ./files/sites_available_default
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: "0644"
  become: true

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: true
